### ISSUE TITLE
[design] 마이페이지 글 목록 퍼블리싱 작업

### ISSUE THREAD

**Issue by minzyee** [BEpyeong/BEpyeong#2]
## 작업할 내용 간략한 설명
- 마이페이지의 글 목록 퍼블리싱 작업을 할 예정입니다.

## 구현 방법 및 예상 화면
- 해당 페이지에 필요한 글 목록 UI를 퍼블리싱 할 예정입니다.

## 특이사항
- 없습니다 ~ !

**Comment by yedol1** [comment]
화이팅~!🌸
